kind: Service
apiVersion: v1
metadata:
  name: lab-spring-boot-docker
spec:
  type: NodePort
  selector:
    app: lab-spring-boot-docker
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30310
    targetPort: 8080
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lab-spring-boot-docker
  labels:
    app: lab-spring-boot-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-spring-boot-docker
  template:
    metadata:
      labels:
        app: lab-spring-boot-docker
    spec:
      containers:
      - name: lab-spring-boot-docker
        image: twinspark81/lab-spring-boot-docker:0.0.1
        ports:
        - name: http
          containerPort: 8080
